### ISSUE TITLE
jump-related and skimming checks on ship management page not working as expected

### ISSUE THREAD

**Issue by SkriptKitty** [pullmangames/pullmangames.github.io#52]
I don't know whether this is actually a bug or just that these pieces aren't fully implemented yet, but the astrogation check, engine power check, and skimming skill checks on the ship management page aren't working the way I would expect them to.

Specifically, I can select the character that I want to make the roll and then press the "Roll" button. After doing that, it doesn't give an indication of success/failure; instead, it clears out the character selection I made and disables the "Roll" button.

**Comment by EighthMonth** [comment]
It's probably not fully implemented yet. Clicking the roll button intentionally clears the selected character. Additionally, it sets the ng-model variable with the results of the roll. Most likely, nobody has hooked anything up to those results.

**Comment by SkriptKitty** [comment]
I think I fixed this. If you guys want to double-check to confirm, we can probably close this out.
